#!/usr/bin/env python3

import json
import locale
import sys
import reports
import emails

def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(
      car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  locale.setlocale(locale.LC_ALL, 'en_US.UTF8')
  max_revenue = {"revenue": 0}
  max_sales = {"total_sales": 0}
  year_popularity = {}
  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item
    # Record max sales
    if item["total_sales"] > max_sales["total_sales"]:
      max_sales = item
    # Record the most popular car_year
    if item["car"]["car_year"] in year_popularity.keys():
      year_popularity[item["car"]["car_year"]] += item["total_sales"]
    else:
      year_popularity[item["car"]["car_year"]] = item["total_sales"]
  max_year = ["0", 0]
  for year in year_popularity.keys():
    if year_popularity[year] > max_year[1]:
      max_year[0] = year
      max_year[1] = year_popularity[year]
  summary = [
    "The {} generated the most revenue: ${}".format(
      format_car(max_revenue["car"]), max_revenue["revenue"]),
  ]
  summary.append("The {} had the most sales: {}".format(format_car(max_sales["car"]), max_sales["total_sales"]))
  summary.append("The most popular year was {} with {} sales.".format(max_year[0], max_year[1]))

  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data


def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("../car_sales.json")
  summary = process_data(data)
  print(summary)
  # Turn this summary into a PDF report
  filename = "cars.pdf"
  body = summary[0] + '<br/>' + summary[1] + '<br/>' + summary[2]
  title = "Sales summary for last month"
  table_data = cars_dict_to_table(data)
  reports.generate(filename, title, body, table_data)

  # Send the PDF report as an email attachment
  sender = "automation@example.com"
  recipient = "student-02-ab48b4aef8f8@example.com"
  subject = "Sales summary for last month"
  body = body.replace('<br/>', '\n')
  a_path = "cars.pdf"
  message = emails.generate(sender, recipient, subject, body, a_path)
  emails.send(message)

if __name__ == "__main__":
  main(sys.argv)
